server:
  port: 8081
  servlet:
    encoding:
      force-response: true
    session:
      # persistent: true # 是否在重启之间保存session
      timeout: 1m

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
    converters:
      preferred-json-mapper: gson
#  main:
#    allow-circular-references: true

#debug: true